export {
  convertEventToV2,
  deletePersonalCalendar,
  deleteSyncCalendar,
  getEvent,
  getPersonalCalendar,
  getPrimaryCalendar,
  getSyncCalendar,
  getSyncPolicy,
  listEvents,
  listEventsV2,
  listPersonalCalendarCandidates,
  listPersonalCalendars,
  listPersonalEvents,
  listSyncCalendarCandidates,
  matchEvent,
  registerSyncInterest,
  syncCalendarPermissions,
  validateSyncPolicy,
} from "./client.js";
